name: Step 7 - Connect Agent to MCP Tools

on:
  push:
    branches:
      - main
    paths:
      - 'packages/node-os-mcp/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: get_step
        run: |
          step=$(cat ./.github/steps/-step.txt)
          echo "current_step=$step" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_node_os_mcp_directory:
    name: On addition of node-os-mcp directory
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template &&
          needs.get_current_step.outputs.current_step == '7' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Confirm node-os-mcp folder exists
        id: check_node_os_mcp
        run: |
          if [ -d "packages/node-os-mcp" ]; then
            echo "agent_exists=true" >> $GITHUB_OUTPUT
          else
            echo "agent_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update to Step 8
        if: steps.check_node_os_mcp.outputs.agent_exists == 'true'
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 7
          to_step: 8